package com.meetbhavesh.notification.domain.enums;

public enum AuditEventType {
    NOTIFICATION_ACCEPTED,
    NOTIFICATION_REJECTED,
    DUPLICATE_SUPPRESSED,
    ROUTING_DECISION_MADE,
    DELIVERY_QUEUED,
    DELIVERY_ATTEMPTED,
    DELIVERY_SUCCEEDED,
    DELIVERY_FAILED,
    RETRY_SCHEDULED,
    NOTIFICATION_EXPIRED
}
