spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    driver-class-name: org.postgresql.Driver
    username: notification
    password: notification
  jpa:
    hibernate:
      ddl-auto: validate
